In [2]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy import linalg
from scipy.linalg import det
sns.set()

### Zadanie 4

Rozwiązanie przy pomocy implementacji metody eliminacji Gaussa, którą wykorzystuje się do rozwiązywania układu równań liniowych $A\vec{x} = \vec{b}$. Znajdziemy $\vec{x}$. Chcemy otrzymać macierz górnotrojkątną (macierz z zerami poniżej przekątnej), a następnie zapisać rozwiązaia układu w wektorze x

In [2]:
def gauss_eliminate1(A, b):
   
    n = len(A)
    
    for k in range(n):
        # Wybór wiersza z największą wartością bezwzględną w kolumnie k
        max = np.argmax(np.abs(A[k:, k])) + k
        A[[k, max]], b[[k, max]] = A[[max, k]], b[[max, k]]

        # Eliminacja elementów poniżej przekątne
        for i in range(k+1, n):
            factor = A[i, k] / A[k, k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x


In [3]:
A = np.array([[0, 0, 2, 1, 2],
              [0, 1, 0, 2, -1],
              [1, 2, 0, -2, 0],
              [0, 0, 0, -1, 1],
              [0, 1, -1, 1, -1]], dtype = float)

b = np.array([1, 1, -4, -2, -1], dtype = float)

In [4]:
x = gauss_eliminate1(A,b)

In [5]:
print("Rozwiązanie:", x)

Rozwiązanie: [ 2. -2.  1.  1. -1.]


Rozwiązanie przy pomocy funkcji z bibliotki scipy.

In [6]:
A = np.array([[0, 0, 2, 1, 2],
              [0, 1, 0, 2, -1],
              [1, 2, 0, -2, 0],
              [0, 0, 0, -1, 1],
              [0, 1, -1, 1, -1]], dtype = float)

b = np.array([1, 1, -4, -2, -1], dtype = float)

In [7]:
x = linalg.solve(A, b)

In [8]:
print("Rozwiązanie:", x)

Rozwiązanie: [ 2. -2.  1.  1. -1.]


Otrzymaliśmy takie same wyniki.

### Zadanie 5

Rozwiązanie z wykorzystaniem powyższej implementacji metody eliminacji Gaussa. 

Znajdziemy współczynniki wielomianu $y = a_0 + a_1x + a_2x^2 + a_3x^3 + a_4x^4$

In [9]:
A = np.array([[1296, 216, 36, 6, 1], 
              [625, 125, 25, 5, 1], 
              [81, 27, 9, 3, 1],
                [1, 1, 1, 1, 1], 
                [0, 0, 0, 0, 1]], dtype = float)

b = np.array([-2, 2, 3, 1, -1], dtype = float)

In [10]:
a_polynomial = gauss_eliminate1(A,b)

In [11]:
a_polynomial

array([-0.025     ,  0.21666667, -0.875     ,  2.68333333, -1.        ])

In [12]:
coeffs = a_polynomial 
terms = [f'{coeff}x^{len(coeffs)-1-i}' for i, coeff in enumerate(coeffs)]
polynomial = ' + '.join(terms).replace('x^0', '').replace('x^1', 'x').replace(' + -', ' - ')
print("p(x) =", polynomial)

p(x) = -0.024999999999999918x^4 + 0.21666666666666587x^3 - 0.8749999999999978x^2 + 2.683333333333332x - 1.0


Porównanie z funkjcą z biblioteki scipy

In [13]:
A = np.array([[1296, 216, 36, 6, 1], 
              [625, 125, 25, 5, 1], 
              [81, 27, 9, 3, 1],
                [1, 1, 1, 1, 1], 
                [0, 0, 0, 0, 1]], dtype = float)

b = np.array([-2, 2, 3, 1, -1], dtype = float)

In [14]:
an_polynomial = linalg.solve(A, b)

In [15]:
an_polynomial

array([-0.025     ,  0.21666667, -0.875     ,  2.68333333, -1.        ])

In [16]:
coeffs = an_polynomial 
terms = [f'{coeff}x^{len(coeffs)-1-i}' for i, coeff in enumerate(coeffs)]
polynomial = ' + '.join(terms).replace('x^0', '').replace('x^1', 'x').replace(' + -', ' - ')
print("p(x) =", polynomial)

p(x) = -0.024999999999999956x^4 + 0.21666666666666623x^3 - 0.8749999999999989x^2 + 2.6833333333333327x - 1.0


Wyniki się pokrywają.

# Zadanie 6

Rozwiążemy układ $A\vec{x} = \vec{b}$, znajdziemy $\det(A)$ oraz $\vec{b}$.

In [17]:
A = np.array([[3.5, 2.77, -0.76, 1.80],
               [-1.80, 2.68, 3.44, -0.09],
                 [0.27, 5.07, 6.9, 1.61], 
                 [1.71, 5.45, 2.68, 1.71]], dtype = float)

b = np.array([7.31, 4.23, 13.85, 11.55], dtype = float)

In [18]:
x = gauss_eliminate1(A, b)

In [19]:
x

array([1., 1., 1., 1.])

In [20]:
A = np.array([[3.5, 2.77, -0.76, 1.80],
               [-1.80, 2.68, 3.44, -0.09],
                 [0.27, 5.07, 6.9, 1.61], 
                 [1.71, 5.45, 2.68, 1.71]], dtype = float)

Ax = np.dot(A,x)

In [21]:
Ax

array([ 7.31,  4.23, 13.85, 11.55])

In [22]:
b = np.array([7.31, 4.23, 13.85, 11.55], dtype = float)

r = b -Ax

In [23]:
r

array([8.88178420e-16, 0.00000000e+00, 1.77635684e-15, 1.77635684e-15])

## Porównanie z funkcją wbudowaną

In [24]:
A = np.array([[3.5, 2.77, -0.76, 1.80],
               [-1.80, 2.68, 3.44, -0.09],
                 [0.27, 5.07, 6.9, 1.61], 
                 [1.71, 5.45, 2.68, 1.71]], dtype = float)

b = np.array([7.31, 4.23, 13.85, 11.55], dtype = float)

In [25]:
x = linalg.solve(A, b)

In [26]:
x

array([1., 1., 1., 1.])

In [27]:
A = np.array([[3.5, 2.77, -0.76, 1.80], [-1.80, 2.68, 3.44, -0.09], [0.27, 5.07, 6.9, 1.61], [1.71, 5.45, 2.68, 1.71]], dtype = float)
Ax = np.dot(A, x)
Ax

array([ 7.31,  4.23, 13.85, 11.55])

In [28]:
b = np.array([7.31, 4.23, 13.85, 11.55], dtype = float)
r = b - Ax

In [29]:
r

array([0.00000000e+00, 8.88178420e-16, 1.77635684e-15, 1.77635684e-15])

## Wyzanczenie wyznacznika macierzy A

In [30]:
def get_det(A):
    n = len(A)
    determinant_sign = 1

    for k in range(n):
        # Szukanie elementu maksymalnego w k-tej kolumnie
        max_row = np.argmax(np.abs(A[k:n, k])) + k

        # Zamiana miejscami k-tego wiersza z wierszem z maksymalnym elementem
        if k != max_row:
            A[[k, max_row]] = A[[max_row, k]]
            determinant_sign *= -1  # Zmiana znaku wyznacznika przy zamianie wierszy

        if A[k, k] == 0:
            return 0  # Wyznacznik jest zerowy, gdy na przekątnej pojawia się zero

        # Eliminacja Gaussa
        for i in range(k + 1, n):
            factor = A[i, k] / A[k, k]
            A[i, k + 1:] -= factor * A[k, k + 1:]

    detA = determinant_sign * np.prod(np.diagonal(A))
    return detA


In [31]:
A = np.array([[3.5, 2.77, -0.76, 1.80],
               [-1.80, 2.68, 3.44, -0.09],
                 [0.27, 5.07, 6.9, 1.61], 
                 [1.71, 5.45, 2.68, 1.71]], dtype = float)

detA = get_det(A)

In [32]:
detA

-0.22579734000000884

## Wyznacznik funkcją wbudowaną

In [33]:
A = np.array([[3.5, 2.77, -0.76, 1.80],
               [-1.80, 2.68, 3.44, -0.09],
                 [0.27, 5.07, 6.9, 1.61], 
                 [1.71, 5.45, 2.68, 1.71]], dtype = float)

detA = linalg.det(A)

In [34]:
detA

-0.22579733999999502

# Zadanie 7

Rozwiążemy układ $A\vec{x} = \vec{b}$.

In [35]:
A = np.array([[10, -2, -1, 2, 3, 1, -4, 7],
              [5, 11, 3, 10, -3, 3, 3, -4],
              [7, 12, 1, 5, 3, -12, 2, 3],
              [8, 7, -2, 1, 3, 2, 2, 4],
              [2, -15, -1, 1, 4, -1, 8, 3],
              [4, 2, 9, 1, 12, -1, 4, 1],
              [-1, 4, -7, -1, 1, 1, -1, -3],
              [-1, 3, 4, 1, 3, -4, 7, 6]], dtype = float)

b = np.array([0, 12, -5, 3, -25, -26, 9, -7], dtype = float)

In [36]:
x = gauss_eliminate1(A, b)

In [37]:
x

array([-1.,  1., -1.,  1., -1.,  1., -1.,  1.])

Porównanie z funkcją z biblioteki scipy

In [38]:
A = np.array([[10, -2, -1, 2, 3, 1, -4, 7],
              [5, 11, 3, 10, -3, 3, 3, -4],
              [7, 12, 1, 5, 3, -12, 2, 3],
              [8, 7, -2, 1, 3, 2, 2, 4],
              [2, -15, -1, 1, 4, -1, 8, 3],
              [4, 2, 9, 1, 12, -1, 4, 1],
              [-1, 4, -7, -1, 1, 1, -1, -3],
              [-1, 3, 4, 1, 3, -4, 7, 6]], dtype = float)

b = np.array([0, 12, -5, 3, -25, -26, 9, -7], dtype = float)

In [39]:
x = linalg.solve(A,b)

In [40]:
x

array([-1.,  1., -1.,  1., -1.,  1., -1.,  1.])

Wyniki się pokrywają

### Zadanie 8

Aby obliczyć odwrotność macierzy, stosujemy metodę eliminacji Gaussa na rozszerzonej macierzy, która składa się z oryginalnej macierzy A i macierzy jednostkowej (identyczności). Poniżej zmodyfikowana funkcja gauss_elimination do obsługi macierzy zamiast pojedynczego wektora.

In [6]:
def gauss_eliminate2(A, B):
    n = len(A)  

    for k in range(n):
        # Wybór wiersza z największą wartością bezwzględną w kolumnie k
        max = np.argmax(np.abs(A[k:, k])) + k
        A[[k, max]], B[[k, max]] = A[[max, k]], B[[max, k]] 

        for i in range(k+1, n):
            factor = A[i, k] / A[k, k]  # Obliczenie współczynnika
            A[i, k:] -= factor * A[k, k:]  # Aktualizacja wierszy macierzy A
            B[i, :] -= factor * B[k, :]  # Aktualizacja wierszy macierzy B

    
    for i in range(n-1, -1, -1):
        B[i, :] -= np.dot(A[i, i+1:], B[i+1:, :])  # Odejmowanie dotychczasowych rozwiązań
        B[i, :] /= A[i, i]  # Dzielenie przez współczynnik na przekątnej

    return B 

In [7]:
def get_matrix_inverse(matrix):
    n = len(matrix)  
    identity_matrix = np.identity(n)  
    inverse_matrix = gauss_eliminate2(matrix, identity_matrix)  

    return inverse_matrix  

In [43]:
A = np.array([[2, -1, 0, 0, 0, 0],
              [-1, 2, -1, 0, 0, 0],
              [0, -1, 2, -1, 0, 0],
              [0, 0, -1, 2, -1, 0],
              [0, 0, 0, -1, 2, -1],
              [0, 0, 0, 0, -1, 5]], dtype = float)

inverse_A = get_matrix_inverse(A)

Macierz A

In [44]:
A = np.array([[2, -1, 0, 0, 0, 0],
              [-1, 2, -1, 0, 0, 0],
              [0, -1, 2, -1, 0, 0],
              [0, 0, -1, 2, -1, 0],
              [0, 0, 0, -1, 2, -1],
              [0, 0, 0, 0, -1, 5]], dtype = float)
A

array([[ 2., -1.,  0.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.],
       [ 0.,  0., -1.,  2., -1.,  0.],
       [ 0.,  0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0.,  0., -1.,  5.]])

Macierz odwrotna $A^{-1}$

In [45]:
inverse_A

array([[0.84, 0.68, 0.52, 0.36, 0.2 , 0.04],
       [0.68, 1.36, 1.04, 0.72, 0.4 , 0.08],
       [0.52, 1.04, 1.56, 1.08, 0.6 , 0.12],
       [0.36, 0.72, 1.08, 1.44, 0.8 , 0.16],
       [0.2 , 0.4 , 0.6 , 0.8 , 1.  , 0.2 ],
       [0.04, 0.08, 0.12, 0.16, 0.2 , 0.24]])

Sprawdzenie

In [46]:
A = np.array([[2, -1, 0, 0, 0, 0],
              [-1, 2, -1, 0, 0, 0],
              [0, -1, 2, -1, 0, 0],
              [0, 0, -1, 2, -1, 0],
              [0, 0, 0, -1, 2, -1],
              [0, 0, 0, 0, -1, 5]], dtype = float)

A_inv = linalg.inv(A)

In [47]:
A_inv

array([[0.84, 0.68, 0.52, 0.36, 0.2 , 0.04],
       [0.68, 1.36, 1.04, 0.72, 0.4 , 0.08],
       [0.52, 1.04, 1.56, 1.08, 0.6 , 0.12],
       [0.36, 0.72, 1.08, 1.44, 0.8 , 0.16],
       [0.2 , 0.4 , 0.6 , 0.8 , 1.  , 0.2 ],
       [0.04, 0.08, 0.12, 0.16, 0.2 , 0.24]])

Macierz odwortna nie jest macierzą trójdiagonalną.

### Zadanie 9

In [8]:
A = np.array([[1, 3, -9, 6, 4],
             [2, -1, 6, 7, 1],
             [3, 2, -3, 15, 5],
             [8, -1, 1, 4, 2],
             [11, 1, -2, 18, 7]], dtype = float)

inverse_A = get_matrix_inverse(A)


In [10]:
A = np.array([[1, 3, -9, 6, 4],
             [2, -1, 6, 7, 1],
             [3, 2, -3, 15, 5],
             [8, -1, 1, 4, 2],
             [11, 1, -2, 18, 7]], dtype = float)

print("Macierz A:\n", A)
print("Macierz odwrotna A^(-1):\n", inverse_A)

Macierz A:
 [[ 1.  3. -9.  6.  4.]
 [ 2. -1.  6.  7.  1.]
 [ 3.  2. -3. 15.  5.]
 [ 8. -1.  1.  4.  2.]
 [11.  1. -2. 18.  7.]]
Macierz odwrotna A^(-1):
 [[-7.42166231e+14 -7.42166231e+14 -7.42166231e+14 -1.48433246e+15
   1.48433246e+15]
 [-3.52528960e+15 -3.52528960e+15 -3.52528960e+15 -7.05057919e+15
   7.05057919e+15]
 [-5.90359502e+14 -5.90359502e+14 -5.90359502e+14 -1.18071900e+15
   1.18071900e+15]
 [-0.00000000e+00 -0.00000000e+00  1.00000000e+00  1.00000000e+00
  -1.00000000e+00]
 [ 1.50119988e+15  1.50119988e+15  1.50119988e+15  3.00239975e+15
  -3.00239975e+15]]


In [50]:
A = np.array([[1, 3, -9, 6, 4],
             [2, -1, 6, 7, 1],
             [3, 2, -3, 15, 5],
             [8, -1, 1, 4, 2],
             [11, 1, -2, 18, 7]], dtype = float)


np.linalg.inv(A)

array([[-1.06340236e+15, -1.06340236e+15, -1.06340236e+15,
        -2.12680472e+15,  2.12680472e+15],
       [-5.05116121e+15, -5.05116121e+15, -5.05116121e+15,
        -1.01023224e+16,  1.01023224e+16],
       [-8.45888241e+14, -8.45888241e+14, -8.45888241e+14,
        -1.69177648e+15,  1.69177648e+15],
       [-7.02563008e-17, -9.54097912e-18,  1.00000000e+00,
         1.00000000e+00, -1.00000000e+00],
       [ 2.15097296e+15,  2.15097296e+15,  2.15097296e+15,
         4.30194591e+15, -4.30194591e+15]])

In [51]:
get_det(A)

5.928590951498336e-14

In [52]:
A = np.array([[1, 3, -9, 6, 4],
             [2, -1, 6, 7, 1],
             [3, 2, -3, 15, 5],
             [8, -1, 1, 4, 2],
             [11, 1, -2, 18, 7]], dtype = float)


In [53]:
detA = np.linalg.det(A)
detA

4.137662434899883e-14

Macierz jest osobliwa, ponieważ wyznacznik macierzy jest w przybliżeniu 0, zatem nie możemy wyznaczyć jej odwrotności. Z rozwiązania numerycznego otrzymaliśmy błędy zaokrągleń.